NCN-5: PATCH /api/articles/:article_id
Mooose17/BE-News-Project pull request #5
Opened 2022-08-02 13:39 UTC by Mooose17

Uses the fetchArticlesByID function to get article object from array.
updateArticleVotes takes the specific object and updates votes using the value in the req.body.inc_values object.

2022-08-02 14:00 UTC, alexdevdavis requested changes
please ensure that your postgres query updates the database values (rather than tinkering with returned data from db to ostensibly pass a test)

2022-08-02 14:00 UTC, alexdevdavis commented on __tests__/patch-article-id.test.js
> +
if your test hangs a little, it might be worth adding another hook to end connection to the db

2022-08-02 14:00 UTC, alexdevdavis commented on __tests__/patch-article-id.test.js
> +    const expected = {
I'd suggest using article_id as the point of comparison, as that's what the logic of your functions relies on here

2022-08-02 14:00 UTC, alexdevdavis commented on __tests__/patch-article-id.test.js
> +  it("status:201, should take whatever value is passed to incVotes and incriment votes by that value", async () => {
'whatever value' would validate non-numeric values

2022-08-02 14:00 UTC, alexdevdavis commented on __tests__/patch-article-id.test.js
> +    const expected = {
how could you refactor this code so you only have to create this variable once?

2022-08-02 14:00 UTC, alexdevdavis commented on __tests__/patch-article-id.test.js
> +    const expected = {
...and then reassign only votes

2022-08-02 14:00 UTC, alexdevdavis commented on model/patch-article-id.js
> +    return { ...result, votes: newVote };
I'm not convinced that this will actually UPDATE the votes value on the object in the database

2022-08-02 15:50 UTC, scar1377 requested changes
Hi Tommy. Please take a look at the feedback. If you've got any questions, always remember to nchelp

2022-08-02 15:50 UTC, scar1377 commented on __tests__/patch-article-id.test.js
> +    const expected = {
This basically means including article_id in your expected object, because whatever returns will have article_id as one of the properties.

2022-08-02 15:50 UTC, scar1377 commented on __tests__/patch-article-id.test.js
> +});
One more sad path needed. 400 - wrong datatype. .send({inc_votes : "cat"})

2022-08-02 15:50 UTC, scar1377 commented on model/patch-article-id.js
> +    return { ...result, votes: newVote };
I'm not convinced either. Think about having a different query string instead of invoking fetchArticleFromTable. Using the UPDATE query string. For the current solution, the updated votes is not saved in the database

2022-08-03 08:28 UTC, scar1377 approved these changes
Hi Tommy. Please read the feedback, go ahead to change or not change it and then merge to main

2022-08-03 08:28 UTC, scar1377 commented on model/patch-article-id.js
> +  await db.query("UPDATE articles SET votes = $1 WHERE article_id = $2;", [
This way is absolutely fine. Can even do SET votes = votes + $1 to make it easier

2022-08-03 08:29 UTC, merged